import { useNavigate } from "react-router-dom";
import { books, masterPapers, phdPapers } from "../data/mockData";

function LibraryShell({ children }: { children: React.ReactNode }) {
  return <div className="lib-root"><style>{`
    .lib-root{min-height:100vh;background:#fbfaf7;color:#2b261f}.lib-root *{box-sizing:border-box}.lib-wrap{max-width:1180px;margin:0 auto;padding:0 28px}.lib-hero{padding:88px 0 70px;border-bottom:1px solid #ddcfba}.lib-kicker{font-size:10px;letter-spacing:.26em;color:#8b642f}.lib-hero h1{max-width:960px;margin:20px 0 0;font:400 clamp(42px,5vw,68px)/1.32 'Noto Serif TC',Georgia,serif}.lib-hero p{max-width:820px;margin:26px 0 0;color:#746b60;line-height:2}.lib-body{padding:64px 0 110px}.lib-list{border-top:1px solid #ddcfba}.lib-row{display:grid;grid-template-columns:110px minmax(0,1fr) auto;gap:34px;padding:34px 0;border-bottom:1px solid #ddcfba}.lib-index{font:400 18px Georgia,serif;color:#b1874c}.lib-row h2{margin:0;font:400 25px/1.55 'Noto Serif TC',Georgia,serif}.lib-row p{margin:12px 0 0;color:#6f675e;line-height:1.9}.lib-meta{margin-top:13px;color:#9a6f3b;font-size:12px;letter-spacing:.04em}.lib-actions{display:flex;gap:10px;align-items:center}.lib-actions button,.lib-actions a{border:1px solid #c7a16b;background:#fffdf9;color:#805a30;padding:10px 14px;text-decoration:none;font-size:12px;cursor:pointer}.lib-note{margin-top:52px;padding:30px;border:1px solid #d8c8ad;background:linear-gradient(135deg,#fffdf9,#f4ede2)}.lib-note h2{margin:0;font:400 27px/1.5 'Noto Serif TC',Georgia,serif}.lib-note p{max-width:820px;margin:14px 0 0;color:#6f675e;line-height:1.9}.lib-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.lib-panel{padding:30px;border:1px solid #ddcfba;background:#fffdf9}.lib-panel h2{margin:0;font:400 25px/1.5 'Noto Serif TC',Georgia,serif}.lib-panel p{margin:13px 0 0;color:#6f675e;line-height:1.9}.lib-panel ul{margin:22px 0 0;padding-left:20px;color:#6f675e;line-height:1.9}.lib-back{margin-top:34px;border:0;border-bottom:1px solid #a9793e;background:transparent;color:#805a30;padding:0 0 5px;cursor:pointer}@media(max-width:760px){.lib-row{grid-template-columns:54px 1fr}.lib-actions{grid-column:2;justify-self:start;flex-wrap:wrap}.lib-columns{grid-template-columns:1fr}.lib-hero{padding:66px 0 54px}}
  `}</style>{children}</div>;
}

export function BooksCanonical(){
  const navigate=useNavigate();
  return <LibraryShell><section className="lib-hero"><div className="lib-wrap"><div className="lib-kicker">BOOKS · STT PRESS</div><h1>著作正典</h1><p>這裡只呈現已存在於 STT 出版資料中的著作。書籍頁的責任是說清楚作品本身，而不是以黑金商城、過度權威宣稱或 AI 系統話術取代內容。</p></div></section><section className="lib-body"><div className="lib-wrap"><div className="lib-list">{books.map((book,index)=><article className="lib-row" key={book.id}><div className="lib-index">{String(index+1).padStart(2,"0")}</div><div><h2>{book.title}</h2><div className="lib-meta">{book.author}｜{book.publisher}</div>{book.id==="b1"&&<p>《內在法遵》在本網站被定位為內在治理思想正典，處理責任、邊界、節制與判斷主權；不與企業契約、付款、稽核等企業法遵制度混為同一概念。</p>}</div><div className="lib-actions">{book.id==="b1"&&<button onClick={()=>navigate('/books/internal-compliance')}>正典頁</button>}{book.previewUrl&&<a href={book.previewUrl} target="_blank" rel="noreferrer">試閱／預覽 ↗</a>}</div></article>)}</div><div className="lib-note"><h2>出版資料仍需逐本校對。</h2><p>正式上線前，書名、版本、年份、售價、出版狀態與外部預覽連結必須再對照最新出版母檔；網站不得自行修正或補寫不存在的出版資訊。</p></div></div></section></LibraryShell>;
}

export function InternalComplianceCanonical(){
  const navigate=useNavigate();
  const book=books.find((b)=>b.id==='b1');
  return <LibraryShell><section className="lib-hero"><div className="lib-wrap"><div className="lib-kicker">INTERNAL COMPLIANCE · CANON</div><h1>內在法遵</h1><p>《內在法遵》不是企業稽核手冊，也不是契約審查流程。它處理的是一個人在權力、利益、壓力與不確定性中，如何保留自己的責任、邊界與判斷主權。</p></div></section><section className="lib-body"><div className="lib-wrap"><div className="lib-columns"><article className="lib-panel"><h2>思想定位</h2><p>能力可以外包，資訊可以由工具協助，專業可以由不同角色進場；但最後的授權、否決與責任不能因此消失。內在法遵關心的是外部規則進入一個人的判斷後，如何成為不可輕易交換的內在秩序。</p><ul><li>責任不因工具或專業分工而消失</li><li>判斷先有邊界，再追求效率</li><li>不可承擔的錯誤不以短期利益交換</li><li>制度最終要能回到人的自我治理</li></ul></article><article className="lib-panel"><h2>與企業法遵的界線</h2><p>企業法遵與契約治理處理授權、契約、交易、付款、證據、稽核與法律風險；《內在法遵》處理的是內在治理。兩者可以相互支援，但不得在網站上使用同一頁面或同一套概念互相取代。</p><div className="lib-actions" style={{marginTop:22}}><button onClick={()=>navigate('/domains/compliance-contract')}>企業法遵與契約治理 →</button></div></article></div>{book?.previewUrl&&<div className="lib-note"><h2>正式版本</h2><p>{book.title}</p><div className="lib-actions" style={{marginTop:20}}><a href={book.previewUrl} target="_blank" rel="noreferrer">開啟預覽 ↗</a></div></div>}<button className="lib-back" onClick={()=>navigate('/books')}>← 回到著作正典</button></div></section></LibraryShell>;
}

export function ResearchCanonical(){
  const papers=[...phdPapers,...masterPapers];
  return <LibraryShell><section className="lib-hero"><div className="lib-wrap"><div className="lib-kicker">RESEARCH & THESIS</div><h1>研究與論文</h1><p>研究頁只承載可追溯到原始論文的研究資料。這一階段先保留論文題名、類型與正式來源入口；研究問題、方法、樣本、統計結果與結論必須逐篇回到原始論文後再上線。</p></div></section><section className="lib-body"><div className="lib-wrap"><div className="lib-list">{papers.map((paper,index)=><article className="lib-row" key={paper.id}><div className="lib-index">{String(index+1).padStart(2,"0")}</div><div><h2>{paper.title}</h2><div className="lib-meta">{paper.type}</div><p>{paper.enTitle}</p></div><div className="lib-actions">{paper.previewUrl&&<a href={paper.previewUrl} target="_blank" rel="noreferrer">論文預覽 ↗</a>}</div></article>)}</div><div className="lib-note"><h2>不把後來的策略推論冒充既有實證。</h2><p>目前舊研究頁中若存在「研究已證明某治理模型」「量化某策略效果」等延伸文案，正式版一律不沿用，除非原始論文可直接支持該敘述。</p></div></div></section></LibraryShell>;
}
