import { useState } from "react";
import { useNavigate } from "react-router-dom";

type HomeSection = "hero" | "governance" | "positioning" | "strategist" | "insights";
type HomeProps={onNavigate:(page:string)=>void;currentPage?:string;activeSection?:HomeSection;setActiveSection?:(section:HomeSection)=>void};

const focusAreas=[
  ["重大決策","先確認問題、證據與不可承擔的錯誤。","/problems/major-decision"],
  ["企業承接","把個人權威轉成可被組織承接的制度。","/problems/owner-dependence"],
  ["接班治理","讓權力、資訊、責任與價值真正跨過世代。","/problems/succession"],
  ["家族治理","讓所有權、照護責任、異議與退出有共同規則。","/problems/family-ownership"],
  ["策略＋法務","法律位置與商業價值必須同時被判讀。","/problems/strategic-legal"],
  ["AI Governance","能力不等於權力；先界定授權、覆核、停止與責任。","/problems/ai-governance"],
  ["制度失效","找出制度文件與真實運作之間的責任斷點。","/problems/system-failure"],
  ["Founder Legacy","把創辦人的治理記憶轉成可被傳承的制度資產。","/problems/founder-legacy"],
];

const pillars=[
  ["01","Problem","先確認真正要解決的是什麼。"],
  ["02","Evidence","把事實、主張、證據、假設與未知拆開。"],
  ["03","Judgment","先否決不可承擔的錯誤，再談最佳化。"],
  ["04","Governance","讓權力、責任、停止與回復都有制度位置。"],
];

export default function HomeV2(_:HomeProps){
  const nav=useNavigate();
  const [menu,setMenu]=useState(false);
  const go=(path:string)=>{setMenu(false);nav(path);window.scrollTo({top:0,behavior:"smooth"})};

  return <div className="stth"><style>{`
    .stth{--paper:#fbfaf7;--ivory:#f6f1e7;--ivory2:#efe6d6;--ink:#2b261f;--muted:#756b5e;--gold:#b1874c;--gold2:#8b642f;--line:#dccdb6;min-height:100vh;background:var(--paper);color:var(--ink);font-family:Inter,"Noto Sans TC",system-ui,sans-serif}.stth *{box-sizing:border-box}.stth-wrap{max-width:1240px;margin:auto;padding:0 30px}.stth-serif{font-family:"Noto Serif TC",Georgia,serif}
    .stth-head{position:absolute;z-index:20;left:0;right:0;top:0;height:86px;background:rgba(251,250,247,.94);border-bottom:1px solid rgba(177,135,76,.22);backdrop-filter:blur(12px)}.stth-headin{height:86px;display:flex;align-items:center;gap:32px}.stth-brand{border:0;background:transparent;padding:0;cursor:pointer;text-align:left;color:var(--ink)}.stth-brand strong{display:block;font:500 18px/1.1 Georgia,serif;letter-spacing:.08em}.stth-brand small{display:block;margin-top:5px;font-size:8px;letter-spacing:.26em;color:var(--gold2)}.stth-nav{margin-left:auto;display:flex;align-items:center;gap:2px}.stth-nav button{height:86px;border:0;background:transparent;padding:0 13px;font-size:11px;color:#655c51;cursor:pointer}.stth-start{height:auto!important;margin-left:12px!important;border:1px solid #c7a36e!important;border-radius:999px!important;padding:11px 18px!important;color:#7d592d!important}.stth-menubtn{display:none;margin-left:auto;border:0;background:transparent;color:var(--ink);font-size:24px;cursor:pointer}
    .stth-hero{position:relative;min-height:760px;padding-top:86px;display:flex;align-items:center;overflow:hidden;background:var(--paper)}.stth-hero-media{position:absolute;inset:86px 0 0 39%;background:url('/images/bg-portal-columns.png') center/cover no-repeat}.stth-hero-media:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,var(--paper) 0%,rgba(251,250,247,.96) 11%,rgba(251,250,247,.72) 29%,rgba(251,250,247,.18) 58%,rgba(251,250,247,.04) 100%)}.stth-hero-copy{position:relative;z-index:2;width:53%;padding:120px 0 96px}.stth-kicker{font-size:10px;letter-spacing:.28em;color:var(--gold2)}.stth-hero h1{margin:22px 0 0;font:400 clamp(50px,5.5vw,80px)/1.22 "Noto Serif TC",Georgia,serif;letter-spacing:-.03em}.stth-lead{max-width:650px;margin-top:26px;font-size:16px;line-height:2;color:var(--muted)}.stth-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:32px}.stth-actions button{border:1px solid #b58a51;background:transparent;color:#79552c;padding:13px 20px;cursor:pointer}.stth-actions .primary{background:#a9793e;color:#fff;border-color:#a9793e}.stth-meta{display:grid;grid-template-columns:repeat(3,max-content);gap:36px;margin-top:48px}.stth-meta div{padding-right:34px;border-right:1px solid var(--line)}.stth-meta div:last-child{border-right:0}.stth-meta b{display:block;font:400 28px Georgia,serif;color:#aa7c42}.stth-meta span{display:block;margin-top:6px;font-size:11px;color:var(--muted)}
    .stth-pillars{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:#fffdf9}.stth-pillargrid{display:grid;grid-template-columns:repeat(4,1fr)}.stth-pillar{min-height:180px;padding:30px 28px;border-right:1px solid var(--line)}.stth-pillar:last-child{border-right:0}.stth-pillar span{font:400 13px Georgia,serif;color:var(--gold2)}.stth-pillar h3{font:400 21px/1.5 "Noto Serif TC",Georgia,serif;margin:18px 0 0}.stth-pillar p{margin:10px 0 0;color:var(--muted);font-size:13px;line-height:1.75}
    .stth-section{padding:100px 0;border-bottom:1px solid var(--line);background:var(--paper)}.stth-section.soft{background:linear-gradient(135deg,#f5efe5 0%,#fbfaf7 70%)}.stth-title{margin:16px 0 0;max-width:920px;font:400 clamp(34px,4vw,54px)/1.42 "Noto Serif TC",Georgia,serif}.stth-desc{max-width:780px;margin-top:18px;color:var(--muted);line-height:2}.stth-focus{display:grid;grid-template-columns:repeat(4,1fr);margin-top:44px;border-top:1px solid var(--line);border-left:1px solid var(--line)}.stth-focus button{min-height:205px;padding:26px;border:0;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:#fffdf9;text-align:left;cursor:pointer;color:var(--ink);transition:background .25s ease,transform .25s ease}.stth-focus button:hover{background:#f7f1e7;transform:translateY(-2px)}.stth-focus b{display:block;color:var(--gold2);font:400 11px/1 Georgia,serif;letter-spacing:.12em}.stth-focus h3{margin:18px 0 0;font:400 20px/1.5 "Noto Serif TC",Georgia,serif}.stth-focus p{margin:10px 0 0;color:var(--muted);font-size:13px;line-height:1.75}.stth-focus em{display:block;margin-top:18px;color:#99703d;font-style:normal}
    .stth-belief{display:grid;grid-template-columns:1fr 1.05fr;gap:70px;align-items:center}.stth-belief-media{height:430px;background:url('/images/bg-strategist-spotlight.png') center/cover no-repeat;border:1px solid var(--line);box-shadow:0 26px 58px rgba(99,76,45,.1);position:relative}.stth-belief-media:after{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(255,253,249,.08),rgba(246,238,225,.24))}.stth-belief .stth-title{max-width:600px}.stth-rule{width:52px;height:1px;background:#b88e55;margin:28px 0}.stth-belief p{color:var(--muted);line-height:2}.stth-belief button{margin-top:24px;border:0;border-bottom:1px solid #a9793e;background:transparent;padding:0 0 5px;color:#805a30;cursor:pointer}
    .stth-final{text-align:center;padding:105px 28px;background:linear-gradient(180deg,#faf8f3,#f1e8da);border-bottom:1px solid var(--line)}.stth-final h2{margin:16px auto 0;max-width:900px;font:400 clamp(36px,4.4vw,60px)/1.4 "Noto Serif TC",Georgia,serif}.stth-final p{max-width:760px;margin:22px auto 0;color:var(--muted);line-height:2}.stth-final button{margin-top:30px;border:1px solid #ad7f45;background:#ad7f45;color:#fff;padding:13px 22px;cursor:pointer}
    .stth-drawer{position:fixed;z-index:100;inset:0;background:rgba(245,239,229,.78);backdrop-filter:blur(9px);display:flex;justify-content:flex-end}.stth-drawerpanel{width:min(430px,92vw);height:100%;background:#fffdf9;padding:85px 34px 40px;box-shadow:-20px 0 60px rgba(82,63,42,.12)}.stth-close{position:absolute;right:26px;top:20px;border:0;background:transparent;font-size:27px}.stth-drawerpanel button:not(.stth-close){width:100%;padding:17px 0;border:0;border-bottom:1px solid var(--line);background:transparent;text-align:left;font:400 18px "Noto Serif TC",Georgia,serif;color:var(--ink)}
    @media(max-width:980px){.stth-nav{display:none}.stth-menubtn{display:block}.stth-hero-media{inset:86px 0 0 0;opacity:.52}.stth-hero-media:after{background:rgba(251,250,247,.83)}.stth-hero-copy{width:100%}.stth-pillargrid,.stth-focus{grid-template-columns:repeat(2,1fr)}.stth-belief{grid-template-columns:1fr}.stth-meta{grid-template-columns:repeat(3,1fr);gap:0}.stth-meta div{padding-right:16px;margin-right:16px}}
    @media(max-width:640px){.stth-wrap{padding:0 20px}.stth-hero{min-height:700px}.stth-hero-copy{padding:105px 0 75px}.stth-hero h1{font-size:46px}.stth-meta{grid-template-columns:1fr;gap:16px}.stth-meta div{border-right:0;border-bottom:1px solid var(--line);padding:0 0 14px;margin:0}.stth-pillargrid,.stth-focus{grid-template-columns:1fr}.stth-pillar{border-right:0;border-bottom:1px solid var(--line)}.stth-focus button{min-height:170px}.stth-section{padding:78px 0}.stth-belief-media{height:300px}}
  `}</style>

  <header className="stth-head"><div className="stth-wrap stth-headin"><button className="stth-brand" onClick={()=>go('/')}><strong>STT GOVERNANCE</strong><small>STRATEGY · GOVERNANCE · JUDGMENT</small></button><nav className="stth-nav"><button onClick={()=>go('/problems')}>你正在面對什麼</button><button onClick={()=>go('/how-stt-works')}>如何判讀</button><button onClick={()=>go('/insights')}>專欄判讀</button><button onClick={()=>go('/publications')}>出版研究</button><button onClick={()=>go('/stt')}>關於 STT</button><button className="stth-start" onClick={()=>go('/start')}>開始治理對話 →</button></nav><button className="stth-menubtn" onClick={()=>setMenu(true)} aria-label="Menu">☰</button></div></header>

  <section className="stth-hero"><div className="stth-hero-media"/><div className="stth-wrap"><div className="stth-hero-copy"><div className="stth-kicker">GOVERNANCE FOR A LONGER TOMORROW</div><h1>讓重要的事，<br/>走得更遠。</h1><p className="stth-lead">STT Governance 協助企業、家族與重大決策者，把未來可能後悔的事情，提前帶到今天理解、判斷、安排與執行。</p><div className="stth-actions"><button className="primary" onClick={()=>go('/problems')}>看看我正在面對的問題</button><button onClick={()=>go('/how-stt-works')}>理解 STT 如何判讀</button></div><div className="stth-meta"><div><b>8</b><span>核心治理情境</span></div><div><b>7</b><span>判讀步驟</span></div><div><b>1</b><span>人類終局責任</span></div></div></div></div></section>

  <section className="stth-pillars"><div className="stth-wrap stth-pillargrid">{pillars.map(([n,t,d])=><div className="stth-pillar" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>

  <section className="stth-section"><div className="stth-wrap"><div className="stth-kicker">CORE GOVERNANCE ISSUES</div><h2 className="stth-title">不是先選服務；先從你正在面對的真實問題開始。</h2><p className="stth-desc">同一個症狀可能來自完全不同的治理根因。真正需要被處理的，不是事件名稱，而是事件背後的權力、證據、責任與不可逆風險。</p><div className="stth-focus">{focusAreas.map((x,i)=><button key={x[0]} onClick={()=>go(x[2])}><b>{String(i+1).padStart(2,'0')}</b><h3>{x[0]}</h3><p>{x[1]}</p><em>進入判讀 →</em></button>)}</div></div></section>

  <section className="stth-section soft"><div className="stth-wrap stth-belief"><div className="stth-belief-media"/><div><div className="stth-kicker">ABOUT STT</div><h2 className="stth-title">好答案不能補救壞問題所造成的戰略盲區。</h2><div className="stth-rule"/><p>STT Governance 的工作不是把問題包裝得更漂亮，而是先確認問題是否成立、證據是否足夠、最壞情境是否可承擔，以及權力與責任是否被正確配置。</p><p>先否決不可承擔錯誤，再驗證合法性與可執行性，最後才進入策略最佳化。</p><button onClick={()=>go('/stt')}>了解 STT Governance →</button></div></div></section>

  <section className="stth-final"><div className="stth-kicker">GOVERNANCE INTAKE</div><h2>現在發生了什麼，而你最不希望接下來發生什麼？</h2><p>不用先知道自己需要哪一種顧問或哪一套工具。從真實情況開始，讓問題先被正確形成。</p><button onClick={()=>go('/start')}>開始治理對話 →</button></section>

  {menu&&<div className="stth-drawer" onClick={()=>setMenu(false)}><div className="stth-drawerpanel" onClick={e=>e.stopPropagation()}><button className="stth-close" onClick={()=>setMenu(false)}>×</button>{[["你正在面對什麼","/problems"],["如何判讀","/how-stt-works"],["專欄判讀","/insights"],["出版研究","/publications"],["人文專案","/projects"],["關於 STT","/stt"],["治理責任","/institution/eric-chuang"],["開始","/start"]].map(([l,p])=><button key={p} onClick={()=>go(p)}>{l}<span style={{float:'right'}}>→</span></button>)}</div></div>}
  </div>;
}
