import { useState } from "react";
import { useNavigate } from "react-router-dom";

type HomeSection = "hero" | "governance" | "positioning" | "strategist" | "insights";
type HomeProps={onNavigate:(page:string)=>void;currentPage?:string;activeSection?:HomeSection;setActiveSection?:(section:HomeSection)=>void};

const problems=[
  ["重大決策","大家都說可以做，我卻不知道真正的風險在哪裡。","major-decision"],
  ["企業承接","公司愈來愈大，重要事情卻仍然只能靠一個人。","owner-dependence"],
  ["接班","二代已經進公司，接班卻始終沒有真正發生。","succession"],
  ["家族與所有權","家族有資產，卻沒有共同決定的方法。","family-ownership"],
  ["策略＋法務","法律上可以做，但商業上到底值不值得。","strategic-legal"],
  ["AI Governance","AI 已經進公司，但沒人知道它可以決定到哪裡。","ai-governance"],
  ["制度失效","制度、SOP 都有，真正出事時卻失效。","system-failure"],
  ["Founder Legacy","我希望把創辦人的思想、企業故事與價值留下來。","founder-legacy"],
];
const methods=["看見","反推","舉證","理解","架構","執行","留下"];
const outcomes=["Decision Brief","GO／CONDITIONAL GO／HOLD／NO-GO","權責矩陣與 Reserved Matters","策略＋法務 Decision Review","接班與家族治理 Roadmap","AI 權限／覆核／停止 SOP","90 日治理啟動與驗收","Founder Legacy／治理記憶"];

export default function HomeV2(_:HomeProps){
  const nav=useNavigate(); const [menu,setMenu]=useState(false);
  const go=(path:string)=>{setMenu(false);nav(path)};
  return <div className="hv-root"><style>{`
    .hv-root{--ink:#2a251f;--muted:#6f675d;--gold:#aa7b3f;--line:#ddcfb9;--paper:#fbfaf7;min-height:100vh;background:var(--paper);color:var(--ink)}.hv-root *{box-sizing:border-box}.hv-wrap{max-width:1200px;margin:auto;padding:0 28px}
    .hv-hero{position:relative;min-height:100svh;background:#fbfaf7 url('/visual-bank/stt/home.webp') right center/cover no-repeat;overflow:hidden}.hv-overlay{position:absolute;inset:0;background:linear-gradient(90deg,rgba(251,250,247,.97) 0%,rgba(251,250,247,.87) 34%,rgba(251,250,247,.34) 56%,rgba(251,250,247,.04) 76%,rgba(251,250,247,0) 100%)}
    .hv-top{position:absolute;z-index:4;left:0;right:0;top:0;height:92px}.hv-menu-btn{position:absolute;right:5.2%;top:38px;width:54px;height:45px;border:0;background:transparent;cursor:pointer}.hv-hero-copy{position:relative;z-index:2;min-height:100svh;display:flex;flex-direction:column;justify-content:center;width:52%;padding:150px 0 130px}.hv-eyebrow{font-size:10px;letter-spacing:.3em;color:var(--gold)}.hv-hero h1{margin:24px 0 0;font:400 clamp(46px,5.3vw,78px)/1.28 'Noto Serif TC',Georgia,serif;letter-spacing:-.025em}.hv-lead{max-width:670px;margin-top:28px;color:var(--muted);font-size:16px;line-height:2}.hv-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:34px}.hv-actions button{border:1px solid #a9793e;background:transparent;color:#80592f;padding:13px 19px;cursor:pointer}.hv-actions button:first-child{background:#a9793e;color:#fff}
    .hv-drawer{position:fixed;z-index:90;inset:0;background:rgba(39,34,29,.14);backdrop-filter:blur(7px);display:flex;justify-content:flex-end}.hv-drawer-panel{width:min(480px,92vw);height:100%;background:#fbfaf7;padding:95px 42px 42px;box-shadow:-25px 0 60px rgba(61,49,37,.12)}.hv-close{position:absolute;right:30px;top:24px;border:0;background:transparent;font-size:28px;cursor:pointer}.hv-drawer-label{font-size:10px;letter-spacing:.26em;color:var(--gold);margin-bottom:22px}.hv-link{display:flex;width:100%;justify-content:space-between;padding:18px 0;border:0;border-bottom:1px solid var(--line);background:transparent;font:400 20px 'Noto Serif TC',Georgia,serif;text-align:left;cursor:pointer;color:var(--ink)}
    .hv-section{padding:105px 0;border-top:1px solid var(--line)}.hv-heading{margin:15px 0 0;max-width:860px;font:400 clamp(34px,4vw,54px)/1.38 'Noto Serif TC',Georgia,serif}.hv-desc{max-width:760px;margin-top:18px;color:var(--muted);line-height:2}.hv-problems{margin-top:45px;border-top:1px solid var(--line)}.hv-problem{display:grid;grid-template-columns:70px 170px 1fr 44px;gap:20px;align-items:center;padding:25px 0;border-bottom:1px solid var(--line);cursor:pointer}.hv-problem .n{font:18px Georgia;color:#ad824d}.hv-problem .cat{font-size:12px;color:#8a6a43}.hv-problem .q{font:400 19px/1.65 'Noto Serif TC',Georgia,serif}.hv-problem .arr{color:#a9793e;font-size:22px}.hv-dark{background:#2c2823;color:#f7f1e7}.hv-dark .hv-heading{color:#fffaf1}.hv-dark .hv-desc{color:#c9c0b4}.hv-dark .hv-eyebrow{color:#d6b07a}.hv-mis{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin-top:45px;background:#4b443c;border:1px solid #4b443c}.hv-mis div{min-height:170px;background:#332e29;padding:28px;font:400 19px/1.7 'Noto Serif TC',Georgia,serif}.hv-mis b{display:block;margin-bottom:16px;color:#d5ae78;font:10px Inter,sans-serif;letter-spacing:.19em}
    .hv-method{margin-top:45px;border-top:1px solid var(--line);display:grid;grid-template-columns:repeat(7,1fr)}.hv-step{padding:25px 16px;border-right:1px solid var(--line);min-height:140px}.hv-step:last-child{border-right:0}.hv-step span{font:14px Georgia;color:#ad824d}.hv-step strong{display:block;margin-top:18px;font:400 19px 'Noto Serif TC',Georgia,serif}.hv-outcomes{display:grid;grid-template-columns:repeat(2,1fr);margin-top:45px;border-left:1px solid var(--line);border-top:1px solid var(--line)}.hv-outcome{padding:25px;min-height:105px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:#fff;font:400 18px/1.7 'Noto Serif TC',Georgia,serif}
    .hv-proof{display:grid;grid-template-columns:1.1fr .9fr;gap:22px;margin-top:46px}.hv-proof-card{border:1px solid var(--line);background:#fff;padding:38px;min-height:290px}.hv-proof-card h3{margin:0;font:400 28px/1.5 'Noto Serif TC',Georgia,serif}.hv-proof-card p{margin-top:18px;color:var(--muted);line-height:1.9}.hv-proof-card button{margin-top:26px;border:0;border-bottom:1px solid #a9793e;background:transparent;color:#80582e;padding-bottom:4px;cursor:pointer}
    .hv-legacy{background:linear-gradient(135deg,#eee5d8,#fbfaf7)}.hv-legacy-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:8vw;align-items:center}.hv-folio{position:relative;height:430px}.hv-folio:before{content:'';position:absolute;left:12%;top:13%;width:67%;height:68%;background:linear-gradient(145deg,#dfd0ba,#faf4ea);border:1px solid #aa8758;box-shadow:0 22px 44px rgba(74,55,35,.12);transform:rotate(-4deg)}.hv-folio:after{content:'';position:absolute;left:20%;top:21%;width:62%;height:61%;background:#fffdf8;border:1px solid #d3c0a3;transform:rotate(2deg)}.hv-wax{position:absolute;right:19%;bottom:17%;z-index:2;width:54px;height:54px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#d2ad73,#9a6535 63%,#704528)}
    .hv-authority{display:grid;grid-template-columns:1fr 1fr;gap:7vw;align-items:start}.hv-roles{border-top:1px solid var(--line)}.hv-role{display:grid;grid-template-columns:170px 1fr;gap:20px;padding:20px 0;border-bottom:1px solid var(--line)}.hv-role strong{font:400 14px Georgia;color:#8e6637}.hv-role span{color:var(--muted);line-height:1.7}.hv-final{background:#2c2823;color:#f8f1e7;text-align:center;padding:100px 28px}.hv-final h2{margin:14px auto 0;max-width:850px;font:400 clamp(34px,4vw,54px)/1.4 'Noto Serif TC',Georgia,serif}.hv-final p{max-width:740px;margin:22px auto 0;color:#c9c0b4;line-height:2}.hv-final button{margin-top:30px;border:1px solid #c69a5d;background:#c69a5d;color:#2a241e;padding:13px 22px;cursor:pointer}
    @media(max-width:900px){.hv-hero{background-position:68% center}.hv-overlay{background:rgba(251,250,247,.86)}.hv-hero-copy{width:100%;padding-top:140px}.hv-problem{grid-template-columns:50px 1fr}.hv-problem .cat{grid-column:2}.hv-problem .q{grid-column:2}.hv-problem .arr{display:none}.hv-mis{grid-template-columns:1fr}.hv-method{grid-template-columns:1fr}.hv-step{border-right:0;border-bottom:1px solid var(--line)}.hv-outcomes,.hv-proof,.hv-legacy-grid,.hv-authority{grid-template-columns:1fr}}
  `}</style>
  <section id="hero" className="hv-hero"><div className="hv-overlay"/><div className="hv-top"><button aria-label="Menu" className="hv-menu-btn" onClick={()=>setMenu(true)}/></div><div className="hv-wrap"><div className="hv-hero-copy"><div className="hv-eyebrow">STT GOVERNANCE</div><h1>很多事情，不是無法處理；而是往往等到太晚才開始處理。</h1><p className="hv-lead">協助企業、家族與重大決策者，把未來可能後悔的事情，提前帶到今天理解、判斷、安排與執行。</p><div className="hv-actions"><button onClick={()=>go('/problems')}>看看我正在面對的問題</button><button onClick={()=>go('/how-stt-works')}>如何判讀</button></div></div></div></section>
  {menu&&<div className="hv-drawer" onClick={()=>setMenu(false)}><div className="hv-drawer-panel" onClick={e=>e.stopPropagation()}><button className="hv-close" onClick={()=>setMenu(false)}>×</button><div className="hv-drawer-label">STT GOVERNANCE</div>{[['你正在面對什麼','/problems'],['如何判讀','/how-stt-works'],['專欄判讀','/insights'],['出版研究','/publications'],['人文專案','/projects'],['關於 STT','/stt'],['治理責任','/institution/eric-chuang'],['開始','/start']].map(([l,p])=><button className="hv-link" key={p} onClick={()=>go(p)}>{l}<span>→</span></button>)}</div></div>}
  <section id="problems" className="hv-section"><div className="hv-wrap"><div className="hv-eyebrow">PROBLEM FINDER</div><h2 className="hv-heading">現在發生了什麼，而你最不希望接下來發生什麼？</h2><p className="hv-desc">不用先知道自己需要公司治理、法律、家族、接班還是 AI。先從你正在面對的真實情況開始。</p><div className="hv-problems">{problems.map((x,i)=><div className="hv-problem" key={x[2]} onClick={()=>go(`/problems/${x[2]}`)}><div className="n">{String(i+1).padStart(2,'0')}</div><div className="cat">{x[0]}</div><div className="q">{x[1]}</div><div className="arr">→</div></div>)}</div></div></section>
  <section className="hv-section hv-dark"><div className="hv-wrap"><div className="hv-eyebrow">WHY ORGANIZATIONS MISJUDGE</div><h2 className="hv-heading">明明有專業團隊，為什麼重要決定仍然會做錯？</h2><p className="hv-desc">很多失敗不是沒有人努力，而是問題定錯、證據錯置、責任漂移或不可逆後果太晚才被看見。</p><div className="hv-mis">{['把症狀當成真正問題。','把大家都知道當成證據。','把法律上可以當成值得做。','只看成功機率，不看最大損失。','提出方案的人同時審查自己。','事情結束，經驗卻沒有留下來。'].map((x,i)=><div key={x}><b>0{i+1}</b>{x}</div>)}</div></div></section>
  <section id="how-stt-works" className="hv-section"><div className="hv-wrap"><div className="hv-eyebrow">HOW WE JUDGE</div><h2 className="hv-heading">不是先給答案；先建立一條值得相信的判斷程序。</h2><div className="hv-method">{methods.map((x,i)=><div className="hv-step" key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div><div className="hv-actions"><button onClick={()=>go('/how-stt-works')}>完整理解判讀方法</button></div></div></section>
  <section className="hv-section"><div className="hv-wrap"><div className="hv-eyebrow">WHAT YOU CAN GET</div><h2 className="hv-heading">最後不是得到一份漂亮報告，而是得到下一步可以做的東西。</h2><div className="hv-outcomes">{outcomes.map(x=><div className="hv-outcome" key={x}>{x}</div>)}</div></div></section>
  <section id="intelligence" className="hv-section"><div className="hv-wrap"><div className="hv-eyebrow">JUDGMENT LIBRARY & CANON</div><h2 className="hv-heading">先從一個問題看見思考，再決定要不要走得更深。</h2><div className="hv-proof"><div className="hv-proof-card"><h3>專欄判讀不是內容倉庫，而是一座 Problem & Judgment Library。</h3><p>用最容易誤判、最容易踩雷的真實問題，讓讀者看到問題如何被重新定義、舉證與反推。</p><button onClick={()=>go('/insights')}>進入專欄判讀 →</button></div><div className="hv-proof-card"><h3>出版與研究，把一次理解變成可以被承接的知識。</h3><p>書籍、論文與研究不是首頁的商品格，而是當讀者需要把問題想深時，可以進入的正典與研究入口。</p><button onClick={()=>go('/publications')}>進入出版研究 →</button></div></div></div></section>
  <section className="hv-section hv-legacy"><div className="hv-wrap hv-legacy-grid"><div className="hv-folio"><div className="hv-wax"/></div><div><div className="hv-eyebrow">HUMANISTIC / FOUNDER LEGACY</div><h2 className="hv-heading">有些重要的事情，如果今天沒有被理解、沒有被留下，未來的人就只能重新猜一次。</h2><p className="hv-desc">把創辦人的判斷、家族記憶、企業文化與生命故事，在仍然能說、能修正的時候，轉成下一代可以理解的知識資產。</p><div className="hv-actions"><button onClick={()=>go('/projects')}>進入人文專案</button></div></div></div></section>
  <section id="authority" className="hv-section"><div className="hv-wrap hv-authority"><div><div className="hv-eyebrow">GOVERNANCE AUTHORITY</div><h2 className="hv-heading">專業可以分工，最終判斷不能沒有人承擔。</h2><p className="hv-desc">AI 是治理幕僚與 Intelligence Layer；律師、會計師、稅務與其他專業者在各自責任範圍提供正式判斷；STT 負責把問題、證據、專業衝突、可逆性與結果重新放回同一張桌上。</p></div><div className="hv-roles">{[['Problem Framing','決定真正需要被回答的是什麼。'],['Authority Allocation','決定 AI 與各專業者何時、為什麼進場。'],['Conflict Arbitration','遇到不同事實與專業意見時要求重新驗證。'],['Risk Acceptance','判斷哪些風險可以承擔，哪些不可逆錯誤應被否決。'],['Final Governance Judgment','最終治理判讀由莊鈞翔博士承擔。']].map(x=><div className="hv-role" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></div></section>
  <section className="hv-final"><div className="hv-eyebrow">GOVERNANCE INTAKE</div><h2>不用先知道自己需要哪一種顧問。先把正在發生的事情說清楚。</h2><p>告訴 STT：現在發生了什麼、最不希望接下來發生什麼，以及希望事情最後變成什麼。</p><button onClick={()=>go('/start')}>開始</button></section>
  </div>
}