import { useState, type ReactNode } from "react";
import { BrowserRouter, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { ArrowRight, BookOpen, CalendarDays, FileText, Landmark, Menu, Network, ScrollText, Users, X } from "lucide-react";

const directory = [
  ["創會理事長", "莊鈞翔 博士", "中華企業策略永續發展學會 創辦人"],
  ["副理事長", "范英峰", "鎂宥新工程有限公司 總經理"],
  ["秘書長", "黃朝福 會計師", "朝陽會計師事務所 所長"],
  ["常務理事", "陳錚程", "玉山銀行 襄理"],
  ["理事", "謝秉錡 律師", "謝秉錡律師事務所 主持律師"],
  ["理事", "高毓謙 律師", "博理法律事務所"],
  ["理事", "林柏劭 律師", "欣成法律事務所 主持律師"],
  ["理事", "賴祺元 律師", "賴祺元律師事務所 所長"],
  ["理事", "劉煒達 律師", "亞森銧國際法律事務所 所長"],
  ["理事", "林政男 律師", "上海申浩律師事務所 合夥律師"],
  ["候補理事", "游筑雅", "鈺田工業有限公司 業務經理"],
  ["常務監事", "廖經舜", "旭研電機有限公司 總經理"],
  ["監事", "李克成 建築師", "李克成建築師事務所 所長"],
  ["監事", "林家豪", "樂業國際事業有限公司 執行長"],
  ["候補監事", "陳冠宏", "裕富數位資融股份有限公司 副理"],
] as const;

const navItems = [
  ["關於學會", "/about"], ["組織治理", "/governance"], ["策略治理聯席會", "/council"], ["會員與入會", "/membership"],
  ["活動與大會", "/events"], ["知識與研究", "/knowledge"], ["章程與公告", "/charter"],
] as const;

const charterHighlights = [
  ["宗旨", "推廣公司治理法遵精神，促進企業智庫策略有效應用，建構企業界、民間團體及學術界之跨界交流平台，強化風險控管並提升企業永續發展動能。"],
  ["策略圭臬", "策略為先、治理為本、管理為終。"],
  ["組織區域", "以全國行政區域為組織區域，主管機關為內政部。"],
  ["理事會", "理事 9 人，含常務理事 3 人，其中 1 人為理事長、1 人為副理事長；候補理事 1 人。"],
  ["監事會", "監事 3 人、候補監事 1 人、常務監事 1 人。"],
  ["任期", "理事、監事均為無給職，任期二年。"],
] as const;

function GlobalStyle() {
  return <style>{`
    body{margin:0!important;background:#f8f5ee!important;color:#29231d!important;font-family:Inter,"Noto Sans TC",system-ui,sans-serif!important;overflow-x:hidden}.gcsda *{box-sizing:border-box}.gcsda{--paper:#f8f5ee;--surface:#fffdf8;--ink:#29231d;--muted:#71685e;--gold:#b18449;--gold2:#8e642f;--line:#dacbb5;min-height:100vh;background:var(--paper);color:var(--ink)}
    .g-wrap{max-width:1220px;margin:auto;padding:0 28px}.g-header{position:sticky;top:0;z-index:60;height:82px;background:rgba(255,253,248,.94);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}.g-header-in{height:82px;display:flex;align-items:center}.g-brand{border:0;background:transparent;text-align:left;cursor:pointer;padding:0}.g-brand b{font:500 19px/1.2 "Noto Serif TC",Georgia,serif;letter-spacing:.05em}.g-brand small{display:block;margin-top:5px;color:var(--gold2);font-size:8px;letter-spacing:.22em}.g-nav{margin-left:auto;display:flex;align-items:center}.g-nav button{height:82px;padding:0 12px;border:0;background:transparent;color:#62594f;font-size:11px;cursor:pointer}.g-nav button.active{color:var(--gold2)}.g-stt{margin-left:14px!important;height:auto!important;border:1px solid #c8a26e!important;padding:10px 13px!important;color:var(--gold2)!important}.g-menu{display:none;margin-left:auto;border:0;background:transparent}.g-drawer{position:fixed;inset:0;z-index:90;background:rgba(40,34,29,.14);backdrop-filter:blur(7px);display:flex;justify-content:flex-end}.g-drawer-panel{width:min(440px,92vw);height:100%;background:#fffdf8;padding:86px 34px}.g-drawer-panel button{width:100%;padding:17px 0;border:0;border-bottom:1px solid var(--line);background:transparent;text-align:left;font:400 18px "Noto Serif TC",Georgia,serif;cursor:pointer}.g-close{position:absolute;right:24px;top:22px!important;width:auto!important;border:0!important}
    .g-hero{min-height:calc(100svh - 82px);position:relative;overflow:hidden;display:flex;align-items:center;border-bottom:1px solid var(--line)}.g-hero:after{content:"";position:absolute;right:-8vw;top:-12vh;width:60vw;height:60vw;border:1px solid rgba(177,132,73,.22);border-radius:50%;box-shadow:0 0 0 80px rgba(177,132,73,.035),0 0 0 160px rgba(177,132,73,.025)}.g-hero-grid{position:absolute;right:2%;top:5%;width:52%;height:84%;opacity:.35;background-image:linear-gradient(rgba(177,132,73,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(177,132,73,.16) 1px,transparent 1px);background-size:54px 54px;mask-image:linear-gradient(90deg,transparent,#000)}.g-hero-copy{position:relative;z-index:3;width:57%;padding:105px 0 110px}.g-kicker{color:var(--gold2);font-size:10px;letter-spacing:.28em;text-transform:uppercase}.g-hero h1,.g-page h1{font:400 clamp(42px,5vw,74px)/1.3 "Noto Serif TC",Georgia,serif;margin:22px 0 0;letter-spacing:-.02em}.g-hero p{max-width:690px;color:var(--muted);font-size:17px;line-height:2;margin:26px 0 0}.g-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}.g-actions button,.g-actions a{border:1px solid #b78c55;background:transparent;color:#805a30;padding:13px 18px;text-decoration:none;font-size:13px;cursor:pointer}.g-actions .primary{background:#a9793e;color:white}.g-seal{position:absolute;z-index:2;right:9%;bottom:12%;width:min(350px,24vw);filter:drop-shadow(0 25px 45px rgba(82,57,29,.12));opacity:.92}
    .g-section{padding:95px 0;border-bottom:1px solid var(--line)}.g-title{font:400 clamp(30px,3.4vw,48px)/1.4 "Noto Serif TC",Georgia,serif;margin:14px 0 0}.g-lead{max-width:780px;color:var(--muted);line-height:2;margin:18px 0 0}.g-grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line);border:1px solid var(--line);margin-top:42px}.g-card{background:var(--surface);padding:30px;min-height:205px}.g-card span{font:11px Georgia;color:var(--gold2);letter-spacing:.15em}.g-card h3{font:400 23px/1.5 "Noto Serif TC",Georgia,serif;margin:16px 0 0}.g-card p{color:var(--muted);line-height:1.85;font-size:14px}.g-stat{font:400 38px Georgia;color:var(--gold2);margin-top:16px}.g-dark{background:#302b26;color:#f8f1e6}.g-dark .g-lead{color:#c9c0b4}.g-dark .g-card{background:#37312b}.g-dark .g-card p{color:#cfc5b8}.g-dark .g-card h3{color:#fffaf1}
    .g-page{padding:90px 0 120px}.g-page-head{padding:55px 0 60px;border-bottom:1px solid var(--line);margin-bottom:60px}.g-page-head p{max-width:800px;color:var(--muted);line-height:2}.g-list{border-top:1px solid var(--line);margin-top:34px}.g-row{display:grid;grid-template-columns:150px 1fr;gap:30px;padding:24px 0;border-bottom:1px solid var(--line)}.g-row b{color:var(--gold2);font:400 14px Georgia}.g-row div{line-height:1.85}.g-directory{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border-top:1px solid var(--line);border-left:1px solid var(--line);margin-top:36px}.g-person{padding:26px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:#fffdf8}.g-person small{color:var(--gold2);letter-spacing:.12em}.g-person h3{font:400 22px "Noto Serif TC",Georgia,serif;margin:10px 0 7px}.g-person p{color:var(--muted);font-size:13px;margin:0;line-height:1.6}.g-photo{margin-top:38px;border:1px solid var(--line);background:white;padding:10px}.g-photo img{display:block;width:100%}.g-event{display:grid;grid-template-columns:180px 1fr auto;gap:32px;align-items:start;padding:30px 0;border-bottom:1px solid var(--line)}.g-event time{font:400 20px Georgia;color:var(--gold2)}.g-event h3{font:400 24px "Noto Serif TC",Georgia,serif;margin:0}.g-event p{color:var(--muted);line-height:1.8}.g-badge{border:1px solid #c8a26e;padding:8px 10px;font-size:10px;color:var(--gold2);white-space:nowrap}.g-footer{padding:50px 0;background:#2e2924;color:#e9dfd1}.g-footer-grid{display:grid;grid-template-columns:1fr auto;gap:35px;align-items:end}.g-footer p{max-width:650px;color:#bfb5a8;line-height:1.8;font-size:13px}.g-footer a{color:#d9b57f;text-decoration:none;margin-left:18px;font-size:12px}
    @media(max-width:1050px){.g-nav{display:none}.g-menu{display:block}.g-hero-copy{width:70%}.g-seal{width:240px;right:2%}.g-grid3,.g-directory{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.g-wrap{padding:0 20px}.g-hero-copy{width:100%;padding:90px 0 130px}.g-seal{width:150px;right:4%;bottom:4%;opacity:.32}.g-grid3,.g-directory{grid-template-columns:1fr}.g-row,.g-event{grid-template-columns:1fr;gap:10px}.g-footer-grid{grid-template-columns:1fr}.g-footer a{margin:0 14px 0 0}}
  `}</style>;
}

function Shell({children}:{children:ReactNode}){
  const nav=useNavigate(); const loc=useLocation(); const [open,setOpen]=useState(false);
  const go=(p:string)=>{setOpen(false);nav(p);window.scrollTo({top:0,behavior:"smooth"})};
  return <div className="gcsda"><GlobalStyle/><header className="g-header"><div className="g-wrap g-header-in"><button className="g-brand" onClick={()=>go("/")}><b>GCSDA</b><small>中華企業策略永續發展學會</small></button><nav className="g-nav">{navItems.map(([l,p])=><button key={p} className={loc.pathname===p?"active":""} onClick={()=>go(p)}>{l}</button>)}<button className="g-stt" onClick={()=>window.location.href="https://stt-003.vercel.app"}>STT Governance ↗</button></nav><button className="g-menu" onClick={()=>setOpen(true)} aria-label="Menu"><Menu/></button></div></header>{open&&<div className="g-drawer" onClick={()=>setOpen(false)}><div className="g-drawer-panel" onClick={e=>e.stopPropagation()}><button className="g-close" onClick={()=>setOpen(false)}><X/></button>{navItems.map(([l,p])=><button key={p} onClick={()=>go(p)}>{l}</button>)}<button onClick={()=>window.location.href="https://stt-003.vercel.app"}>STT Governance ↗</button></div></div>}<main>{children}</main><footer className="g-footer"><div className="g-wrap g-footer-grid"><div><b>中華企業策略永續發展學會｜GCSDA</b><p>連結企業、專業與學術，讓策略、治理、法遵與永續不只停留於理念，而能形成可持續推進的制度與共同體。</p></div><div><a href="https://line.me/R/ti/p/@387nbnjs" target="_blank" rel="noreferrer">會員與聯絡</a><a href="https://stt-003.vercel.app">STT Governance</a></div></div></footer></div>;
}

function Home(){const nav=useNavigate();return <><section className="g-hero"><div className="g-hero-grid"/><div className="g-wrap"><div className="g-hero-copy"><div className="g-kicker">GCSDA · NATIONAL PROFESSIONAL ASSOCIATION</div><h1>策略為先，治理為本，管理為終。</h1><p>中華企業策略永續發展學會，致力於推廣公司治理法遵精神，連結企業界、專業界與學術界，讓策略思維、責任邊界與永續治理形成可以共同實踐的制度力量。</p><div className="g-actions"><button className="primary" onClick={()=>nav("/about")}>認識學會</button><button onClick={()=>nav("/membership")}>會員與入會</button></div></div></div><img className="g-seal" src="/images/gcsda-logo.png" alt="GCSDA"/></section><section className="g-section"><div className="g-wrap"><div className="g-kicker">INSTITUTIONAL PURPOSE</div><h2 className="g-title">不是把活動辦多，而是先把一個值得被信賴的治理組織建立起來。</h2><p className="g-lead">第一年度的工作重點放在法定立案、組織治理、策略治理聯席會、知識資產與電子化作業，使學會可以跨越任期持續累積專業與公共信任。</p><div className="g-grid3"><div className="g-card"><Landmark/><span>01 LEGAL FOUNDATION</span><h3>依法完成全國性社會團體立案</h3><p>內政部台內團字第 1140030747 號，建立會員大會、理事會、監事會與正式章程秩序。</p></div><div className="g-card"><Network/><span>02 STRATEGIC COUNCIL</span><h3>把法律、會計、策略與產業專業接進來</h3><p>逐步形成策略治理聯席會，讓不同專業在重大議題上可以協作，而非各自留下片段答案。</p></div><div className="g-card"><BookOpen/><span>03 KNOWLEDGE ASSETS</span><h3>讓治理形成可累積的知識資產</h3><p>透過講座、研究、出版與會務紀錄，把一次交流沉澱成下一次可以引用與承接的共同知識。</p></div></div></div></section><section className="g-section g-dark"><div className="g-wrap"><div className="g-kicker">2026 ASSEMBLY</div><h2 className="g-title">第一屆第二次會員大會暨第三次理監事聯席會議</h2><p className="g-lead">2026 年 8 月 16 日，學會結合理監事會議、會員交流、專題講座與餐敘，並以「從企業策略到永續治理」作為治理主題。</p><div className="g-grid3"><div className="g-card"><span>FORMAL ASSEMBLY</span><div className="g-stat">08.16</div><p>法定會務與會員共同決定。</p></div><div className="g-card"><span>GOVERNANCE LECTURE</span><h3>從企業策略到永續治理</h3><p>從策略判讀、制度設計、責任邊界、信任底線與永續承接展開。</p></div><div className="g-card"><span>COMMUNITY</span><h3>會員 × 理監事 × 顧問 × 企業 × 學術</h3><p>讓學會成為跨界治理共同體，而不是單一活動品牌。</p></div></div></div></section></>}

function PageHead({kicker,title,lead}:{kicker:string;title:string;lead:string}){return <div className="g-page-head"><div className="g-kicker">{kicker}</div><h1>{title}</h1><p>{lead}</p></div>}
function About(){return <div className="g-page"><div className="g-wrap"><PageHead kicker="ABOUT GCSDA" title="一個以企業策略、治理、法遵與永續為核心的全國性專業社群。" lead="學會不是 STT Governance 的部門，而是依法成立、具有自己會員、理監事、章程與會務責任的獨立專業組織；兩者在治理生態系中互相連結，但保持制度身分清楚。"/><div className="g-list"><div className="g-row"><b>法定名稱</b><div>中華企業策略永續發展學會</div></div><div className="g-row"><b>立案</b><div>內政部台內團字第 1140030747 號</div></div><div className="g-row"><b>組織區域</b><div>全國行政區域</div></div><div className="g-row"><b>主管機關</b><div>內政部；目的事業並受各該事業主管機關指導、監督。</div></div><div className="g-row"><b>核心方向</b><div>企業策略、公司治理法遵、跨界交流、風險控管、產學研合作與永續發展。</div></div></div></div></div>}
function Governance(){return <div className="g-page"><div className="g-wrap"><PageHead kicker="ORGANIZATION & ACCOUNTABILITY" title="會務不是人治，而是會員大會、理事會與監事會共同承擔。" lead="公開組織角色與責任，是學會建立信任的第一層制度。"/><div className="g-grid3"><div className="g-card"><Users/><span>最高權力機構</span><h3>會員大會</h3><p>章程、理監事選舉、年度計畫、預決算與會員重大權利義務事項，回到會員共同決定。</p></div><div className="g-card"><Landmark/><span>執行治理</span><h3>理事會</h3><p>理事 9 人、常務理事 3 人，負責會務治理與組織推進。</p></div><div className="g-card"><FileText/><span>監督治理</span><h3>監事會</h3><p>監事 3 人、常務監事 1 人，形成獨立監督位置。</p></div></div><h2 className="g-title" style={{marginTop:70}}>第一屆理監事會名錄</h2><div className="g-directory">{directory.map(([r,n,t])=><div className="g-person" key={`${r}-${n}`}><small>{r}</small><h3>{n}</h3><p>{t}</p></div>)}</div></div></div>}
function Council(){return <div className="g-page"><div className="g-wrap"><PageHead kicker="STRATEGIC GOVERNANCE COUNCIL" title="策略治理聯席會：讓不同專業可以在同一個治理問題上協作。" lead="法律、會計、策略與不同產業專業開始被接進同一個學會治理共同體；目的不是用一個人取代所有專業，而是建立可以跨專業理解、討論與承接的制度場域。"/><div className="g-photo"><img src="/images/group-001.png" alt="策略治理聯席會專業成員"/></div><div className="g-grid3"><div className="g-card"><span>LEGAL</span><h3>法律與法遵</h3><p>辨識權利義務、程序、契約與責任邊界。</p></div><div className="g-card"><span>ACCOUNTING</span><h3>會計與財務</h3><p>讓財務、稅務與會計資訊進入可驗證的決策脈絡。</p></div><div className="g-card"><span>STRATEGY</span><h3>企業策略與治理</h3><p>把個別專業意見放回企業目標、風險與長期承接中理解。</p></div></div></div></div>}
function Membership(){return <div className="g-page"><div className="g-wrap"><PageHead kicker="MEMBERSHIP" title="加入的不是名單，而是一個願意共同建立治理秩序的專業社群。" lead="依現行章程，會員分為個人會員、榮譽會員與贊助會員；正式會員的權利、義務與會費制度均回到章程與理事會審查程序。"/><div className="g-grid3"><div className="g-card"><span>PERSONAL MEMBER</span><h3>個人會員</h3><p>年滿 25 歲、贊同本會宗旨，填具入會申請書，經理事會審查通過並繳納會費。</p><div className="g-stat">2,000</div><p>入會費 NT$2,000；常年會費 NT$2,000。</p></div><div className="g-card"><span>HONORARY MEMBER</span><h3>榮譽會員</h3><p>贊同本會宗旨之公私立機構、團體或個人，經本會邀請擔任。</p></div><div className="g-card"><span>SPONSOR MEMBER</span><h3>贊助會員</h3><p>贊同本會宗旨且對本會無償捐贈之個人、機構或團體，經本會邀請擔任。</p></div></div><div className="g-actions" style={{marginTop:40}}><a className="primary" href="https://line.me/R/ti/p/@387nbnjs" target="_blank" rel="noreferrer">申請入會與聯絡</a></div></div></div>}
function Events(){return <div className="g-page"><div className="g-wrap"><PageHead kicker="ASSEMBLY & PROGRAMS ARCHIVE" title="把每一次會務與交流，留下成為組織可以承接的制度記憶。" lead="活動頁不只呈現照片或最新消息，而是保存會員大會、理監事會、專題講座與重要治理里程碑。"/><div className="g-list"><div className="g-event"><time>2026.08.16</time><div><h3>第一屆第二次會員大會暨第三次理監事聯席會議</h3><p>地點：沐青餐廳。結合理監事聯席會議、會員交流、專題講座與餐敘；專題講座由創會理事長莊鈞翔博士主講「從企業策略到永續治理」。</p></div><span className="g-badge">FORMAL ASSEMBLY</span></div><div className="g-event"><time>2025–2026</time><div><h3>第一年度治理基礎建設</h3><p>完成法定立案、策略治理聯席會、知識資產、網站與電子化作業等制度基礎。</p></div><span className="g-badge">FOUNDATION</span></div></div></div></div>}
function Knowledge(){return <div className="g-page"><div className="g-wrap"><PageHead kicker="KNOWLEDGE & RESEARCH" title="讓學會不只辦活動，也持續形成可以引用、研究與傳承的治理知識。" lead="知識與研究區將逐步承接專題講座、研究成果、出版、企業案例與產學研合作；第一階段先建立正式分類與典藏入口，不虛構尚未完成的研究成果。"/><div className="g-grid3"><div className="g-card"><BookOpen/><span>LECTURES</span><h3>治理專題講座</h3><p>把企業實務與學術思考放在同一個議題場域中。</p></div><div className="g-card"><ScrollText/><span>RESEARCH</span><h3>研究與論文</h3><p>未來收錄經學會確認之研究成果、學術合作與可公開研究資料。</p></div><div className="g-card"><Network/><span>INDUSTRY–ACADEMIA</span><h3>產學研交流</h3><p>建立企業、學術與研究機構之多元交流平台。</p></div></div></div></div>}
function Charter(){return <div className="g-page"><div className="g-wrap"><PageHead kicker="CHARTER & DISCLOSURE" title="章程不是附錄，而是學會權力、責任與會員關係的母法。" lead="本頁先公開最重要的制度摘要；正式全文仍應以學會核定之現行章程版本為準。"/><div className="g-list">{charterHighlights.map(([a,b])=><div className="g-row" key={a}><b>{a}</b><div>{b}</div></div>)}</div><div className="g-actions" style={{marginTop:38}}><a href="https://line.me/R/ti/p/@387nbnjs" target="_blank" rel="noreferrer">索取／核對現行章程</a></div></div></div>}

function AppRoutes(){return <Shell><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/governance" element={<Governance/>}/><Route path="/council" element={<Council/>}/><Route path="/membership" element={<Membership/>}/><Route path="/events" element={<Events/>}/><Route path="/knowledge" element={<Knowledge/>}/><Route path="/charter" element={<Charter/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Shell>}
export default function GCSDAStandalone(){return <BrowserRouter><AppRoutes/></BrowserRouter>}
