import { useState, type ReactNode } from "react";
import { BrowserRouter, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { Menu, X } from "lucide-react";

const directory = [
  ["創會理事長", "莊鈞翔 博士", "中華企業策略永續發展學會 創辦人"],
  ["副理事長", "范英峰", "鎂宥新工程有限公司 總經理"],
  ["秘書長", "黃朝福 會計師", "朝陽會計師事務所 所長"],
  ["常務理事", "陳錚程", "玉山銀行 襄理"],
  ["理事", "謝秉錡 律師", "謝秉錡律師事務所 主持律師"],
  ["理事", "高毓謙 律師", "博理法律事務所"],
  ["理事", "林柏劭 律師", "欣成法律事務所 主持律師"],
  ["理事", "賴祺元 律師", "賴祺元律師事務所 所長"],
  ["理事", "劉煒達 律師", "亞森銧國際法律事務所 所長"],
  ["理事", "林政男 律師", "上海申浩律師事務所 合夥律師"],
  ["候補理事", "游筑雅", "鈺田工業有限公司 業務經理"],
  ["常務監事", "廖經舜", "旭研電機有限公司 總經理"],
  ["監事", "李克成 建築師", "李克成建築師事務所 所長"],
  ["監事", "林家豪", "樂業國際事業有限公司 執行長"],
  ["候補監事", "陳冠宏", "裕富數位資融股份有限公司 副理"],
] as const;

const navItems = [
  ["關於學會", "/about"], ["組織治理", "/governance"], ["策略治理聯席會", "/council"], ["會員與入會", "/membership"],
  ["活動與大會", "/events"], ["知識與研究", "/knowledge"], ["章程與公告", "/charter"],
] as const;

const routeMeta = {
  about: ["INSTITUTIONAL IDENTITY", "關於學會", "一個讓企業、專業與學術能在治理議題上形成長期交流與制度累積的全國性專業社團。", "/images/bg-portal-columns.png"],
  governance: ["INSTITUTIONAL GOVERNANCE", "組織治理", "學會本身先接受治理：權力來源、章程、理監事職權、會員大會與責任邊界，都必須可被理解與追溯。", "/images/gcsda_team_new.png"],
  council: ["STRATEGIC COUNCIL", "策略治理聯席會", "依不同議題連結法律、會計、策略與產業專業，讓跨領域意見進入同一個治理討論框架。", "/images/group-001.png"],
  membership: ["MEMBERSHIP", "會員與入會", "加入學會不是購買服務，而是進入一個以策略、治理、法遵與永續為共同語言的專業共同體。", "/images/gcsda_003.png"],
  events: ["ASSEMBLY & PROGRAMS", "活動與大會", "會員大會、理監事會、專題講座與交流紀錄，以正式機構檔案方式逐年保存。", "/images/gcsda_team_2026.png"],
  knowledge: ["KNOWLEDGE & RESEARCH", "知識與研究", "讓活動不是一次性聚會，而能逐步轉化為研究、出版、講座與可持續累積的治理知識。", "/images/bg-insights-globe.png"],
  charter: ["CHARTER & NOTICE", "章程與公告", "用正式章程與公告說明學會的權力來源、會員權利義務與制度運作。", "/images/paper_corporate_governance.png"],
} as const;

type RouteKey = keyof typeof routeMeta;

const charterHighlights = [
  ["宗旨", "推廣公司治理法遵精神，促進企業智庫策略有效應用，建構企業界、民間團體及學術界之跨界交流平台，強化風險控管並提升企業永續發展動能。"],
  ["策略圭臬", "策略為先、治理為本、管理為終。"],
  ["組織區域", "以全國行政區域為組織區域，主管機關為內政部。"],
  ["理事會", "理事 9 人，含常務理事 3 人，其中 1 人為理事長、1 人為副理事長；候補理事 1 人。"],
  ["監事會", "監事 3 人、候補監事 1 人、常務監事 1 人。"],
  ["任期", "理事、監事均為無給職，任期二年。"],
] as const;

function Styles(){return <style>{`
  body{margin:0!important;background:#faf8f3!important;color:#29241f!important;font-family:Inter,"Noto Sans TC",system-ui,sans-serif!important;overflow-x:hidden}.g2 *{box-sizing:border-box}.g2{--paper:#faf8f3;--surface:#fffdf9;--ink:#29241f;--muted:#746b60;--gold:#b18449;--gold2:#8b622f;--line:#dccdb8;--deep:#302a24;min-height:100vh;background:var(--paper);color:var(--ink)}.g2-wrap{max-width:1220px;margin:auto;padding:0 28px}
  .g2-header{position:sticky;top:0;z-index:60;height:82px;background:rgba(255,253,249,.95);backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}.g2-header-in{height:82px;display:flex;align-items:center}.g2-brand{border:0;background:transparent;text-align:left;cursor:pointer;padding:0}.g2-brand b{font:500 19px/1.2 "Noto Serif TC",Georgia,serif;letter-spacing:.05em}.g2-brand small{display:block;margin-top:5px;color:var(--gold2);font-size:8px;letter-spacing:.22em}.g2-nav{margin-left:auto;display:flex;align-items:center}.g2-nav button{height:82px;padding:0 12px;border:0;background:transparent;color:#62594f;font-size:11px;cursor:pointer}.g2-nav button.active{color:var(--gold2)}.g2-stt{margin-left:14px!important;height:auto!important;border:1px solid #c8a26e!important;padding:10px 13px!important;color:var(--gold2)!important}.g2-menu{display:none;margin-left:auto;border:0;background:transparent}.g2-drawer{position:fixed;inset:0;z-index:90;background:rgba(40,34,29,.14);backdrop-filter:blur(7px);display:flex;justify-content:flex-end}.g2-drawer-panel{width:min(440px,92vw);height:100%;background:#fffdf8;padding:86px 34px}.g2-drawer-panel button{width:100%;padding:17px 0;border:0;border-bottom:1px solid var(--line);background:transparent;text-align:left;font:400 18px "Noto Serif TC",Georgia,serif;cursor:pointer}.g2-close{position:absolute;right:24px;top:22px!important;width:auto!important;border:0!important}
  .g2-home{min-height:calc(100svh - 82px);position:relative;overflow:hidden;display:flex;align-items:center;border-bottom:1px solid var(--line);background:#fffdf9 url('/images/bg-portal-columns.png') right center/cover no-repeat}.g2-home:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(255,253,249,.97) 0%,rgba(255,253,249,.84) 40%,rgba(255,253,249,.18) 68%,rgba(255,253,249,0) 100%)}.g2-home-copy{position:relative;z-index:2;width:58%;padding:110px 0}.g2-kicker{color:var(--gold2);font-size:10px;letter-spacing:.28em}.g2-home h1,.g2-head h1{font:400 clamp(42px,5vw,72px)/1.3 "Noto Serif TC",Georgia,serif;margin:20px 0 0;letter-spacing:-.02em}.g2-home p,.g2-head p{max-width:760px;color:var(--muted);line-height:2;font-size:16px}.g2-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:30px}.g2-actions button,.g2-actions a{border:1px solid #b78c55;background:transparent;color:#805a30;padding:13px 18px;text-decoration:none;font-size:13px;cursor:pointer}.g2-actions .primary{background:#a9793e;color:white}
  .g2-page{padding-bottom:110px}.g2-head{display:grid;grid-template-columns:1fr .9fr;gap:7vw;align-items:center;min-height:520px;border-bottom:1px solid var(--line)}.g2-visual{position:relative;height:350px;margin:0;border:1px solid #dfd2bf;background:#f4eee5;overflow:hidden;box-shadow:0 28px 70px rgba(72,55,36,.10)}.g2-visual img{display:block;width:100%;height:100%;object-fit:cover;filter:saturate(.82) contrast(.96) brightness(1.04);transition:transform .9s cubic-bezier(.22,1,.36,1)}.g2-visual:hover img{transform:scale(1.018)}.g2-visual:after{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(255,253,248,.12),transparent 48%,rgba(149,103,50,.06));box-shadow:inset 0 0 0 12px rgba(255,253,248,.24);pointer-events:none}
  .g2-section{padding:80px 0;border-bottom:1px solid var(--line)}.g2-title{font:400 clamp(30px,3.4vw,48px)/1.4 "Noto Serif TC",Georgia,serif;margin:14px 0 0}.g2-lead{max-width:800px;color:var(--muted);line-height:2;margin:18px 0 0}.g2-grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line);border:1px solid var(--line);margin-top:40px}.g2-card{background:var(--surface);padding:30px;min-height:205px}.g2-card span{font:11px Georgia;color:var(--gold2);letter-spacing:.15em}.g2-card h3{font:400 23px/1.5 "Noto Serif TC",Georgia,serif;margin:16px 0 0}.g2-card p{color:var(--muted);line-height:1.85;font-size:14px}.g2-dark{background:#302b26;color:#f8f1e6}.g2-dark .g2-lead{color:#c9c0b4}.g2-list{border-top:1px solid var(--line);margin-top:34px}.g2-row{display:grid;grid-template-columns:150px 1fr;gap:30px;padding:24px 0;border-bottom:1px solid var(--line)}.g2-row b{color:var(--gold2);font:400 14px Georgia}.g2-row div{line-height:1.85}.g2-directory{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line);margin-top:34px}.g2-person{padding:26px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:#fffdf8}.g2-person small{color:var(--gold2);letter-spacing:.12em}.g2-person h3{font:400 22px "Noto Serif TC",Georgia,serif;margin:10px 0 7px}.g2-person p{color:var(--muted);font-size:13px;margin:0;line-height:1.6}.g2-event{display:grid;grid-template-columns:180px 1fr auto;gap:32px;align-items:start;padding:30px 0;border-bottom:1px solid var(--line)}.g2-event time{font:400 20px Georgia;color:var(--gold2)}.g2-event h3{font:400 24px "Noto Serif TC",Georgia,serif;margin:0}.g2-event p{color:var(--muted);line-height:1.8}.g2-badge{border:1px solid #c8a26e;padding:8px 10px;font-size:10px;color:var(--gold2);white-space:nowrap}.g2-footer{padding:50px 0;background:#2e2924;color:#e9dfd1}.g2-footer-grid{display:grid;grid-template-columns:1fr auto;gap:35px;align-items:end}.g2-footer p{max-width:650px;color:#bfb5a8;line-height:1.8;font-size:13px}.g2-footer a{color:#d9b57f;text-decoration:none;margin-left:18px;font-size:12px}
  @media(max-width:1050px){.g2-nav{display:none}.g2-menu{display:block}.g2-home-copy{width:72%}.g2-grid3,.g2-directory{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.g2-wrap{padding:0 20px}.g2-home-copy{width:100%;padding:90px 0 140px}.g2-head{grid-template-columns:1fr;gap:35px;padding:65px 0}.g2-visual{height:290px}.g2-grid3,.g2-directory{grid-template-columns:1fr}.g2-row,.g2-event{grid-template-columns:1fr;gap:10px}.g2-footer-grid{grid-template-columns:1fr}.g2-footer a{margin:0 14px 0 0}}
`}</style>}

function Shell({children}:{children:ReactNode}){const nav=useNavigate();const loc=useLocation();const[open,setOpen]=useState(false);const go=(p:string)=>{setOpen(false);nav(p);window.scrollTo({top:0,behavior:"smooth"})};return <div className="g2"><Styles/><header className="g2-header"><div className="g2-wrap g2-header-in"><button className="g2-brand" onClick={()=>go("/")}><b>GCSDA</b><small>中華企業策略永續發展學會</small></button><nav className="g2-nav">{navItems.map(([l,p])=><button key={p} className={loc.pathname===p?"active":""} onClick={()=>go(p)}>{l}</button>)}<button className="g2-stt" onClick={()=>window.location.href="https://stt-003-git-rebuild-white-gold-go-67654f-pc5888pc5888s-projects.vercel.app"}>STT Governance ↗</button></nav><button className="g2-menu" onClick={()=>setOpen(true)} aria-label="Menu"><Menu/></button></div></header>{open&&<div className="g2-drawer" onClick={()=>setOpen(false)}><div className="g2-drawer-panel" onClick={e=>e.stopPropagation()}><button className="g2-close" onClick={()=>setOpen(false)}><X/></button>{navItems.map(([l,p])=><button key={p} onClick={()=>go(p)}>{l}</button>)}<button onClick={()=>window.location.href="https://stt-003-git-rebuild-white-gold-go-67654f-pc5888pc5888s-projects.vercel.app"}>STT Governance ↗</button></div></div>}<main>{children}</main><footer className="g2-footer"><div className="g2-wrap g2-footer-grid"><div><b>中華企業策略永續發展學會｜GCSDA</b><p>連結企業、專業與學術，讓策略、治理、法遵與永續不只停留於理念，而能形成可持續推進的制度與共同體。</p></div><div><a href="https://line.me/R/ti/p/@387nbnjs" target="_blank" rel="noreferrer">會員與聯絡</a><a href="https://stt-003-git-rebuild-white-gold-go-67654f-pc5888s-projects.vercel.app">STT Governance</a></div></div></footer></div>}

function PageHead({kind}:{kind:RouteKey}){const[m,t,d,img]=routeMeta[kind];return <div className="g2-wrap"><section className="g2-head"><div><div className="g2-kicker">{m}</div><h1>{t}</h1><p>{d}</p></div><figure className="g2-visual" aria-hidden="true"><img src={img} alt=""/></figure></section></div>}

function Home(){const nav=useNavigate();return <><section className="g2-home"><div className="g2-wrap"><div className="g2-home-copy"><div className="g2-kicker">GCSDA · NATIONAL PROFESSIONAL ASSOCIATION</div><h1>策略為先，<br/>治理為本，<br/>管理為終。</h1><p>中華企業策略永續發展學會，連結企業、專業與學術，讓治理從理念進入制度、交流與實踐。</p><div className="g2-actions"><button className="primary" onClick={()=>nav('/about')}>認識學會</button><button onClick={()=>nav('/membership')}>會員與入會</button></div></div></div></section><section className="g2-section"><div className="g2-wrap"><div className="g2-kicker">INSTITUTIONAL FOUNDATION</div><h2 className="g2-title">一個談治理的組織，本身必須先被治理。</h2><p className="g2-lead">學會依法成立，以會員大會、理事會與監事會構成正式治理架構，並以章程界定會員權利義務與組織職權。</p><div className="g2-grid3">{[["01","正式立案","主管機關為內政部，組織區域為全國。"],["02","會員共同體","個人會員、榮譽會員與贊助會員構成不同參與關係。"],["03","專業協作","連結法律、會計、策略、產業與學術專業。"]].map(x=><div className="g2-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section><section className="g2-section g2-dark"><div className="g2-wrap"><div className="g2-kicker">2026 ASSEMBLY</div><h2 className="g2-title">會務、專題與會員交流，形成可被留下的制度紀錄。</h2><p className="g2-lead">2026 年 8 月 16 日舉行第一屆第二次會員大會暨第三次理監事聯席會議，並以「從企業策略到永續治理」作為專題講座主題。</p><div className="g2-actions"><button className="primary" onClick={()=>nav('/events')}>進入活動典藏</button></div></div></section></>}

function About(){return <div className="g2-page"><PageHead kind="about"/><section className="g2-section"><div className="g2-wrap"><div className="g2-list">{charterHighlights.slice(0,3).map(([a,b])=><div className="g2-row" key={a}><b>{a}</b><div>{b}</div></div>)}</div></div></section></div>}
function Governance(){return <div className="g2-page"><PageHead kind="governance"/><section className="g2-section"><div className="g2-wrap"><div className="g2-kicker">FIRST BOARD & SUPERVISORS</div><h2 className="g2-title">第一屆理監事會</h2><div className="g2-directory">{directory.map(([role,name,title])=><div className="g2-person" key={`${role}-${name}`}><small>{role}</small><h3>{name}</h3><p>{title}</p></div>)}</div></div></section></div>}
function Council(){return <div className="g2-page"><PageHead kind="council"/><section className="g2-section"><div className="g2-wrap"><div className="g2-kicker">PROFESSIONAL COLLABORATION</div><h2 className="g2-title">跨域專業，不等於權責混同。</h2><p className="g2-lead">策略治理聯席會的價值，在於讓不同專業在各自責任邊界內進場，並透過學會平台形成交流、研究與治理實務的共同語言。</p></div></section></div>}
function Membership(){return <div className="g2-page"><PageHead kind="membership"/><section className="g2-section"><div className="g2-wrap"><div className="g2-grid3">{[["個人會員","年滿二十五歲、贊同宗旨，經理事會審查通過並繳納會費。","入會費 NT$2,000｜常年會費 NT$2,000"],["榮譽會員","由學會邀請之公私立機構、團體或個人。","依章程參與"],["贊助會員","贊同宗旨且對學會無償捐贈之個人、機構或團體。","依章程參與"]].map(x=><div className="g2-card" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p><span>{x[2]}</span></div>)}</div><div className="g2-actions"><a className="primary" href="https://line.me/R/ti/p/@387nbnjs" target="_blank" rel="noreferrer">申請入會諮詢</a></div></div></section></div>}
function Events(){return <div className="g2-page"><PageHead kind="events"/><section className="g2-section"><div className="g2-wrap"><div className="g2-event"><time>2026.08.16</time><div><h3>第一屆第二次會員大會暨第三次理監事聯席會議</h3><p>結合理監事聯席會議、會員交流、專題講座與餐敘；專題講座「從企業策略到永續治理」。</p></div><span className="g2-badge">FORMAL ASSEMBLY</span></div></div></section></div>}
function Knowledge(){return <div className="g2-page"><PageHead kind="knowledge"/><section className="g2-section"><div className="g2-wrap"><div className="g2-grid3">{[["研究與治理觀點","累積企業策略、公司治理、法遵與永續相關研究與實務知識。"],["專題講座","以專題講座促進企業、專業與學術界交流。"],["知識資產","讓會務與活動逐步沉澱為可被引用、再學習與傳承的內容。"]].map((x,i)=><div className="g2-card" key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></div></section></div>}
function Charter(){return <div className="g2-page"><PageHead kind="charter"/><section className="g2-section"><div className="g2-wrap"><div className="g2-list">{charterHighlights.map(([a,b])=><div className="g2-row" key={a}><b>{a}</b><div>{b}</div></div>)}</div><div className="g2-card" style={{marginTop:34,minHeight:0}}><span>LEGAL REGISTRATION</span><h3>組織法定立案</h3><p>內政部台內團字第 1140030747 號。</p></div></div></section></div>}

function AppRoutes(){return <Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/governance" element={<Governance/>}/><Route path="/council" element={<Council/>}/><Route path="/membership" element={<Membership/>}/><Route path="/events" element={<Events/>}/><Route path="/knowledge" element={<Knowledge/>}/><Route path="/charter" element={<Charter/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
export default function GCSDAStandaloneV2(){return <BrowserRouter><Shell><AppRoutes/></Shell></BrowserRouter>}
