import { useState, type ReactNode } from "react";
import { BrowserRouter, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { Menu, X } from "lucide-react";

const navItems = [
  ["關於學會", "/about"], ["組織治理", "/governance"], ["策略治理聯席會", "/council"], ["會員與入會", "/membership"],
  ["活動與大會", "/events"], ["知識與研究", "/knowledge"], ["章程與公告", "/charter"],
] as const;

const directory = [
  ["創會理事長", "莊鈞翔 博士", "中華企業策略永續發展學會 創辦人"],
  ["副理事長", "范英峰", "鎂宥新工程有限公司 總經理"],
  ["秘書長", "黃朝福 會計師", "朝陽會計師事務所 所長"],
  ["常務理事", "陳錚程", "玉山銀行 襄理"],
  ["理事", "謝秉錡 律師", "謝秉錡律師事務所 主持律師"],
  ["理事", "高毓謙 律師", "博理法律事務所"],
  ["理事", "林柏劭 律師", "欣成法律事務所 主持律師"],
  ["理事", "賴祺元 律師", "賴祺元律師事務所 所長"],
  ["理事", "劉煒達 律師", "亞森銧國際法律事務所 所長"],
  ["理事", "林政男 律師", "上海申浩律師事務所 合夥律師"],
  ["候補理事", "游筑雅", "鈺田工業有限公司 業務經理"],
  ["常務監事", "廖經舜", "旭研電機有限公司 總經理"],
  ["監事", "李克成 建築師", "李克成建築師事務所 所長"],
  ["監事", "林家豪", "樂業國際事業有限公司 執行長"],
  ["候補監事", "陳冠宏", "裕富數位資融股份有限公司 副理"],
] as const;

const charterHighlights = [
  ["宗旨", "推廣公司治理法遵精神，促進企業智庫策略有效應用，建構企業界、民間團體及學術界之跨界交流平台，強化風險控管並提升企業永續發展動能。"],
  ["策略圭臬", "策略為先、治理為本、管理為終。"],
  ["組織區域", "以全國行政區域為組織區域，主管機關為內政部。"],
  ["理事會", "理事 9 人，含常務理事 3 人，其中 1 人為理事長、1 人為副理事長；候補理事 1 人。"],
  ["監事會", "監事 3 人、候補監事 1 人、常務監事 1 人。"],
  ["任期", "理事、監事均為無給職，任期二年。"],
] as const;

const routeMeta = {
  about:["INSTITUTIONAL IDENTITY","關於學會","一個讓企業、專業與學術能在治理議題上形成長期交流與制度累積的全國性專業社團。","/images/bg-portal-columns.png"],
  governance:["INSTITUTIONAL GOVERNANCE","組織治理","學會本身先接受治理：權力來源、章程、理監事職權、會員大會與責任邊界，都必須可被理解與追溯。","/images/gcsda_team_new.png"],
  council:["STRATEGIC COUNCIL","策略治理聯席會","依不同議題連結法律、會計、策略與產業專業，讓跨領域意見進入同一個治理討論框架。","/images/group-001.png"],
  membership:["MEMBERSHIP","會員與入會","加入學會不是購買服務，而是進入一個以策略、治理、法遵與永續為共同語言的專業共同體。","/images/gcsda_003.png"],
  events:["ASSEMBLY & PROGRAMS","活動與大會","會員大會、理監事會、專題講座與交流紀錄，以正式機構檔案方式逐年保存。","/images/gcsda_team_2026.png"],
  knowledge:["KNOWLEDGE & RESEARCH","知識與研究","讓活動不是一次性聚會，而能逐步轉化為研究、出版、講座與可持續累積的治理知識。","/images/bg-insights-globe.png"],
  charter:["CHARTER & NOTICE","章程與公告","用正式章程與公告說明學會的權力來源、會員權利義務與制度運作。","/images/paper_corporate_governance.png"],
} as const;
type RouteKey=keyof typeof routeMeta;

function Styles(){return <style>{`
  html,body,#root{margin:0;background:#fbfaf7!important;color:#2c271f!important}.g3{--paper:#fbfaf7;--surface:#fffdf9;--soft:#f5efe5;--soft2:#eee3d4;--ink:#2c271f;--muted:#756c60;--gold:#b48a50;--gold2:#8a6230;--line:#ddceb8;min-height:100vh;background:var(--paper);color:var(--ink);font-family:Inter,"Noto Sans TC",system-ui,sans-serif}.g3 *{box-sizing:border-box}.g3-wrap{max-width:1220px;margin:auto;padding:0 30px}
  .g3-head{position:sticky;top:0;z-index:60;height:84px;background:rgba(251,250,247,.95);border-bottom:1px solid rgba(180,138,80,.24);backdrop-filter:blur(12px)}.g3-headin{height:84px;display:flex;align-items:center}.g3-brand{border:0;background:transparent;padding:0;text-align:left;color:var(--ink);cursor:pointer}.g3-brand b{display:block;font:500 19px Georgia,"Noto Serif TC",serif;letter-spacing:.08em}.g3-brand small{display:block;margin-top:5px;color:var(--gold2);font-size:8px;letter-spacing:.19em}.g3-nav{margin-left:auto;display:flex;align-items:center}.g3-nav button{height:84px;padding:0 11px;border:0;background:transparent;color:#655c51;font-size:11px;cursor:pointer}.g3-nav button.active{color:var(--gold2)}.g3-stt{height:auto!important;margin-left:12px!important;border:1px solid #c7a16b!important;border-radius:999px!important;padding:10px 14px!important;color:#7d592e!important}.g3-menu{display:none;margin-left:auto;border:0;background:transparent;color:var(--ink);cursor:pointer}
  .g3-home{position:relative;min-height:690px;display:flex;align-items:center;overflow:hidden;background:var(--paper);border-bottom:1px solid var(--line)}.g3-home-media{position:absolute;inset:0 0 0 44%;background:url('/images/gcsda_002.png') center/cover no-repeat}.g3-home-media:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,var(--paper) 0%,rgba(251,250,247,.95) 16%,rgba(251,250,247,.7) 38%,rgba(251,250,247,.16) 70%,rgba(251,250,247,.03) 100%)}.g3-home-copy{position:relative;z-index:2;width:55%;padding:110px 0}.g3-kicker{font-size:10px;letter-spacing:.27em;color:var(--gold2)}.g3-home h1,.g3-pagehead h1{margin:20px 0 0;font:400 clamp(48px,5.2vw,76px)/1.28 "Noto Serif TC",Georgia,serif;letter-spacing:-.025em}.g3-home p,.g3-pagehead p{max-width:720px;margin-top:24px;color:var(--muted);line-height:2;font-size:15px}.g3-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.g3-actions button,.g3-actions a{border:1px solid #b78c55;background:transparent;color:#805a30;padding:13px 18px;text-decoration:none;font-size:13px;cursor:pointer}.g3-actions .primary{background:#a9793e;color:#fff;border-color:#a9793e}.g3-meta{display:grid;grid-template-columns:repeat(3,max-content);gap:34px;margin-top:46px}.g3-meta div{padding-right:30px;border-right:1px solid var(--line)}.g3-meta div:last-child{border-right:0}.g3-meta b{display:block;font:400 27px Georgia,serif;color:#aa7d43}.g3-meta span{display:block;margin-top:6px;color:var(--muted);font-size:11px}
  .g3-values{background:#fffdf9;border-bottom:1px solid var(--line)}.g3-valuegrid{display:grid;grid-template-columns:repeat(4,1fr)}.g3-value{padding:30px 28px;min-height:180px;border-right:1px solid var(--line)}.g3-value:last-child{border-right:0}.g3-value span{font:400 12px Georgia,serif;color:var(--gold2)}.g3-value h3{margin:18px 0 0;font:400 21px/1.5 "Noto Serif TC",Georgia,serif}.g3-value p{margin:9px 0 0;color:var(--muted);font-size:13px;line-height:1.75}
  .g3-section{padding:94px 0;border-bottom:1px solid var(--line);background:var(--paper)}.g3-section.soft{background:linear-gradient(135deg,#f4eee4,#fbfaf7 68%)}.g3-title{margin:15px 0 0;font:400 clamp(34px,3.8vw,52px)/1.43 "Noto Serif TC",Georgia,serif}.g3-lead{max-width:820px;margin-top:18px;color:var(--muted);line-height:2}.g3-grid3{display:grid;grid-template-columns:repeat(3,1fr);margin-top:40px;border-top:1px solid var(--line);border-left:1px solid var(--line)}.g3-card{background:#fffdf9;padding:28px;min-height:205px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.g3-card span{font:11px Georgia,serif;color:var(--gold2);letter-spacing:.12em}.g3-card h3{font:400 22px/1.5 "Noto Serif TC",Georgia,serif;margin:16px 0 0}.g3-card p{color:var(--muted);font-size:14px;line-height:1.85}.g3-aboutgrid{display:grid;grid-template-columns:1fr 1.05fr;gap:70px;align-items:center}.g3-aboutmedia{height:410px;background:url('/images/bg-portal-columns.png') center/cover no-repeat;border:1px solid var(--line);box-shadow:0 24px 55px rgba(89,68,42,.1)}.g3-rule{width:54px;height:1px;background:#b48a50;margin:28px 0}.g3-aboutgrid p{color:var(--muted);line-height:2}.g3-aboutgrid button{margin-top:24px;border:0;border-bottom:1px solid #a9793e;background:transparent;color:#805a30;padding:0 0 5px;cursor:pointer}.g3-final{text-align:center;padding:96px 28px;background:linear-gradient(180deg,#faf8f3,#f0e7d9);border-bottom:1px solid var(--line)}.g3-final h2{margin:16px auto 0;max-width:880px;font:400 clamp(36px,4.1vw,56px)/1.42 "Noto Serif TC",Georgia,serif}.g3-final p{max-width:740px;margin:22px auto 0;color:var(--muted);line-height:2}
  .g3-page{padding-bottom:100px}.g3-pagehead{display:grid;grid-template-columns:1fr .9fr;gap:6vw;align-items:center;min-height:500px;border-bottom:1px solid var(--line)}.g3-visual{height:350px;border:1px solid var(--line);background:#f5efe5;overflow:hidden;box-shadow:0 24px 56px rgba(89,68,42,.09)}.g3-visual img{display:block;width:100%;height:100%;object-fit:cover;filter:saturate(.82) brightness(1.05)}.g3-list{border-top:1px solid var(--line);margin-top:34px}.g3-row{display:grid;grid-template-columns:160px 1fr;gap:30px;padding:24px 0;border-bottom:1px solid var(--line)}.g3-row b{color:var(--gold2);font:400 14px Georgia,serif}.g3-row div{line-height:1.85}.g3-directory{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line);margin-top:34px}.g3-person{padding:25px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:#fffdf9}.g3-person small{color:var(--gold2);letter-spacing:.1em}.g3-person h3{font:400 21px "Noto Serif TC",Georgia,serif;margin:10px 0 7px}.g3-person p{margin:0;color:var(--muted);font-size:13px;line-height:1.65}.g3-event{display:grid;grid-template-columns:180px 1fr auto;gap:30px;align-items:start;padding:30px 0;border-bottom:1px solid var(--line)}.g3-event time{font:400 19px Georgia,serif;color:var(--gold2)}.g3-event h3{font:400 23px "Noto Serif TC",Georgia,serif;margin:0}.g3-event p{color:var(--muted);line-height:1.8}.g3-badge{border:1px solid #c7a16b;padding:8px 10px;font-size:10px;color:var(--gold2)}
  .g3-footer{padding:48px 0;background:#f5efe5;border-top:1px solid var(--line);color:var(--ink)}.g3-footergrid{display:grid;grid-template-columns:1fr auto;gap:35px;align-items:end}.g3-footer p{max-width:650px;color:var(--muted);line-height:1.8;font-size:13px}.g3-footer a{color:#8b622f;text-decoration:none;margin-left:18px;font-size:12px}.g3-drawer{position:fixed;inset:0;z-index:100;background:rgba(245,239,229,.8);backdrop-filter:blur(9px);display:flex;justify-content:flex-end}.g3-drawerpanel{width:min(430px,92vw);height:100%;background:#fffdf9;padding:86px 34px}.g3-drawerpanel button{width:100%;padding:17px 0;border:0;border-bottom:1px solid var(--line);background:transparent;text-align:left;font:400 18px "Noto Serif TC",Georgia,serif;color:var(--ink)}.g3-close{position:absolute;right:25px;top:22px!important;width:auto!important;border:0!important}
  @media(max-width:1050px){.g3-nav{display:none}.g3-menu{display:block}.g3-home-media{inset:0;opacity:.52}.g3-home-media:after{background:rgba(251,250,247,.84)}.g3-home-copy{width:100%}.g3-valuegrid,.g3-grid3,.g3-directory{grid-template-columns:repeat(2,1fr)}}
  @media(max-width:760px){.g3-wrap{padding:0 20px}.g3-home{min-height:650px}.g3-home-copy{padding:90px 0}.g3-home h1{font-size:46px}.g3-meta{grid-template-columns:1fr;gap:15px}.g3-meta div{border-right:0;border-bottom:1px solid var(--line);padding:0 0 13px}.g3-valuegrid,.g3-grid3,.g3-directory{grid-template-columns:1fr}.g3-value{border-right:0;border-bottom:1px solid var(--line)}.g3-aboutgrid,.g3-pagehead{grid-template-columns:1fr}.g3-pagehead{padding:70px 0}.g3-event{grid-template-columns:1fr}.g3-footergrid{grid-template-columns:1fr}.g3-footer a{margin:0 18px 0 0}}
`}</style>}

function Shell({children}:{children:ReactNode}){const nav=useNavigate();const loc=useLocation();const[open,setOpen]=useState(false);const go=(p:string)=>{setOpen(false);nav(p);window.scrollTo({top:0,behavior:"smooth"})};return <div className="g3"><Styles/><header className="g3-head"><div className="g3-wrap g3-headin"><button className="g3-brand" onClick={()=>go('/')}><b>GCSDA</b><small>中華企業策略永續發展學會</small></button><nav className="g3-nav">{navItems.map(([l,p])=><button key={p} className={loc.pathname===p?"active":""} onClick={()=>go(p)}>{l}</button>)}<button className="g3-stt" onClick={()=>window.location.href='https://stt-003-git-rebuild-white-gold-go-4eafa7-pc5888pc5888s-projects.vercel.app'}>STT Governance ↗</button></nav><button className="g3-menu" onClick={()=>setOpen(true)} aria-label="Menu"><Menu/></button></div></header>{open&&<div className="g3-drawer" onClick={()=>setOpen(false)}><div className="g3-drawerpanel" onClick={e=>e.stopPropagation()}><button className="g3-close" onClick={()=>setOpen(false)}><X/></button>{navItems.map(([l,p])=><button key={p} onClick={()=>go(p)}>{l}</button>)}<button onClick={()=>window.location.href='https://stt-003-git-rebuild-white-gold-go-4eafa7-pc5888pc5888s-projects.vercel.app'}>STT Governance ↗</button></div></div>}<main>{children}</main><footer className="g3-footer"><div className="g3-wrap g3-footergrid"><div><b>中華企業策略永續發展學會｜GCSDA</b><p>連結企業、專業與學術，讓策略、治理、法遵與永續不只停留於理念，而能形成可持續推進的制度與共同體。</p></div><div><a href="https://line.me/R/ti/p/@387nbnjs" target="_blank" rel="noreferrer">會員與聯絡</a><a href="https://stt-003-git-rebuild-white-gold-go-4eafa7-pc5888pc5888s-projects.vercel.app">STT Governance</a></div></div></footer></div>}

function Home(){const nav=useNavigate();return <><section className="g3-home"><div className="g3-home-media"/><div className="g3-wrap"><div className="g3-home-copy"><div className="g3-kicker">NATIONAL PROFESSIONAL ASSOCIATION · TAIWAN</div><h1>讓策略、治理與永續，<br/>成為共同語言。</h1><p>中華企業策略永續發展學會連結企業、專業與學術，以正式組織、章程與跨域交流，累積可被延續的治理知識與制度共同體。</p><div className="g3-actions"><button className="primary" onClick={()=>nav('/about')}>認識學會</button><button onClick={()=>nav('/membership')}>會員與入會</button></div><div className="g3-meta"><div><b>全國性</b><span>專業社團</span></div><div><b>9+3</b><span>理事與監事治理架構</span></div><div><b>2 年</b><span>理監事任期</span></div></div></div></div></section><section className="g3-values"><div className="g3-wrap g3-valuegrid">{[["01","策略為先","先理解方向與問題，再配置資源。"],["02","治理為本","讓權力、責任與程序有正式制度位置。"],["03","跨域共治","法律、會計、策略、產業與學術形成共同語言。"],["04","永續累積","讓活動與交流沉澱為可以被延續的知識資產。"]].map(([n,t,d])=><div className="g3-value" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="g3-section"><div className="g3-wrap"><div className="g3-kicker">INSTITUTIONAL FOUNDATION</div><h2 className="g3-title">一個談治理的組織，本身必須先被治理。</h2><p className="g3-lead">學會依法成立，以會員大會、理事會與監事會構成正式治理架構，並以章程界定會員權利義務與組織職權。</p><div className="g3-grid3">{[["01","正式立案","主管機關為內政部，組織區域為全國。"],["02","會員共同體","個人會員、榮譽會員與贊助會員構成不同參與關係。"],["03","專業協作","連結法律、會計、策略、產業與學術專業。"]].map(x=><div className="g3-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section><section className="g3-section soft"><div className="g3-wrap g3-aboutgrid"><div className="g3-aboutmedia"/><div><div className="g3-kicker">ABOUT GCSDA</div><h2 className="g3-title">把一次性的交流，轉化為可以逐年累積的制度與知識。</h2><div className="g3-rule"/><p>學會的角色不是取代任何單一專業，而是建立正式共同體，讓不同專業在各自責任邊界內進場，形成跨界交流、研究、講座與治理實務的長期累積。</p><button onClick={()=>nav('/governance')}>理解組織治理 →</button></div></div></section><section className="g3-final"><div className="g3-kicker">MEMBERSHIP & COMMUNITY</div><h2>加入的不是一項服務，而是一個治理共同體。</h2><p>以策略、治理、法遵與永續為共同語言，連結企業、專業人士與學術社群。</p><div className="g3-actions" style={{justifyContent:'center'}}><button className="primary" onClick={()=>nav('/membership')}>了解會員與入會</button></div></section></>}

function PageHead({kind}:{kind:RouteKey}){const[m,t,d,img]=routeMeta[kind];return <div className="g3-wrap"><section className="g3-pagehead"><div><div className="g3-kicker">{m}</div><h1>{t}</h1><p>{d}</p></div><figure className="g3-visual"><img src={img} alt=""/></figure></section></div>}
function About(){return <div className="g3-page"><PageHead kind="about"/><section className="g3-section"><div className="g3-wrap"><div className="g3-list">{charterHighlights.slice(0,3).map(([a,b])=><div className="g3-row" key={a}><b>{a}</b><div>{b}</div></div>)}</div></div></section></div>}
function Governance(){return <div className="g3-page"><PageHead kind="governance"/><section className="g3-section"><div className="g3-wrap"><div className="g3-kicker">FIRST BOARD & SUPERVISORS</div><h2 className="g3-title">第一屆理監事會</h2><div className="g3-directory">{directory.map(([role,name,title])=><div className="g3-person" key={`${role}-${name}`}><small>{role}</small><h3>{name}</h3><p>{title}</p></div>)}</div></div></section></div>}
function Council(){return <div className="g3-page"><PageHead kind="council"/><section className="g3-section"><div className="g3-wrap"><div className="g3-kicker">PROFESSIONAL COLLABORATION</div><h2 className="g3-title">跨域專業，不等於權責混同。</h2><p className="g3-lead">策略治理聯席會讓不同專業在各自責任邊界內進場，並透過學會平台形成交流、研究與治理實務的共同語言。</p></div></section></div>}
function Membership(){return <div className="g3-page"><PageHead kind="membership"/><section className="g3-section"><div className="g3-wrap"><div className="g3-grid3">{[["個人會員","年滿二十五歲、贊同宗旨，經理事會審查通過並繳納會費。","入會費 NT$2,000｜常年會費 NT$2,000"],["榮譽會員","由學會邀請之公私立機構、團體或個人。","依章程參與"],["贊助會員","贊同宗旨且對學會無償捐贈之個人、機構或團體。","依章程參與"]].map(x=><div className="g3-card" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p><span>{x[2]}</span></div>)}</div><div className="g3-actions"><a className="primary" href="https://line.me/R/ti/p/@387nbnjs" target="_blank" rel="noreferrer">申請入會諮詢</a></div></div></section></div>}
function Events(){return <div className="g3-page"><PageHead kind="events"/><section className="g3-section"><div className="g3-wrap"><div className="g3-event"><time>2026.08.16</time><div><h3>第一屆第二次會員大會暨第三次理監事聯席會議</h3><p>結合理監事聯席會議、會員交流、專題講座與餐敘；專題講座「從企業策略到永續治理」。</p></div><span className="g3-badge">FORMAL ASSEMBLY</span></div></div></section></div>}
function Knowledge(){return <div className="g3-page"><PageHead kind="knowledge"/><section className="g3-section"><div className="g3-wrap"><div className="g3-grid3">{[["研究與治理觀點","累積企業策略、公司治理、法遵與永續相關研究與實務知識。"],["專題講座","以專題講座促進企業、專業與學術界交流。"],["知識資產","讓會務與活動逐步沉澱為可被引用、再學習與傳承的內容。"]].map((x,i)=><div className="g3-card" key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></div></section></div>}
function Charter(){return <div className="g3-page"><PageHead kind="charter"/><section className="g3-section"><div className="g3-wrap"><div className="g3-list">{charterHighlights.map(([a,b])=><div className="g3-row" key={a}><b>{a}</b><div>{b}</div></div>)}</div><div className="g3-card" style={{marginTop:34,minHeight:0}}><span>LEGAL REGISTRATION</span><h3>組織法定立案</h3><p>內政部台內團字第 1140030747 號。</p></div></div></section></div>}

function AppRoutes(){return <Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/governance" element={<Governance/>}/><Route path="/council" element={<Council/>}/><Route path="/membership" element={<Membership/>}/><Route path="/events" element={<Events/>}/><Route path="/knowledge" element={<Knowledge/>}/><Route path="/charter" element={<Charter/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
export default function GCSDAStandaloneV2(){return <BrowserRouter><Shell><AppRoutes/></Shell></BrowserRouter>}
